linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - gofmt

linters-settings:
  goimports:
    local-prefixes: get_spoons

run:
  timeout: 5m
